### ISSUE TITLE
baseUrl path has no effect

### ISSUE THREAD

**Issue by dinamic** [csarrazi/CsaGuzzleBundle#1]
baseUrl is set to `https://example.com/api`
The url I would like to call is `https://example.com/api/category/some-category-slug`

I should really be using `$client->get('category/some-category-slug')`.

If I do this, however, it does not work.
It tries to call `https://example.com/category/some-category-slug`, which is invalid.

**Comment by benjhoo** [comment]
Hi, 
this issue still currently remains.

In my case adding `/` as suffix doesn't work, `get` method removes my path
