### ISSUE TITLE
jQuery dependency ?

### ISSUE THREAD

**Issue by mickaelandrieu** [csarrazi/CsaGuzzleBundle#10]
Hi,

I saw on https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/Resources/views/Calls/call.html.twig a call to jQuery 2. You can have some conflicts with the jQuery version you may possibly have into your real application, I suggest to use a ``require()`` strategy with aliases or - better imo - to remove this dependency (I can make a PR this way if you agree).

What do you think ? @csarrazi

**Comment by csarrazi** [comment]
There is no risk here. The call to jquery is only made in the profiler's guzzle page. There is no risk here. Moreover, jquery is built inside the bundle's JS toolchain (using grunt + bower). I'm closing the issue.
