### ISSUE TITLE
Cached queries seems to be ignored by middleware history mechanism

### ISSUE THREAD

**Issue by Torgan** [csarrazi/CsaGuzzleBundle#110]
We are having an issue when using cache and profiler at the same time. The cached queries do not appear in the history. 

As a matter of example, lets say I have a page with 7 api calls. On the first hit, I get this (7 success, 0 error). That's what I intend to get.

On a second call, the profiler bar is not what intended (0 success, 0 error), while, accordingly to the twig code, I should get (0 success, 7 cached, 0 error)

![capture d ecran 2015-12-16 a 14 05 45](https://cloud.githubusercontent.com/assets/394503/11841535/4917aade-a3fe-11e5-985d-5ac5d4579a51.png)
![capture d ecran 2015-12-16 a 14 06 37](https://cloud.githubusercontent.com/assets/394503/11841536/491e6464-a3fe-11e5-9ebf-77f3d9ed959e.png)

**Comment by csarrazi** [comment]
Indeed, the problem seems to come from the fact that the cache middleware has no priority, and is actually triggered before the history middleware. Thus, as the response is provided before the history middleware gets the information, the collector doesn't receive any information afterwards.

**Comment by csarrazi** [comment]
This should be very easy to fix, by setting a priority for the cache middleware lower than the one of the history middleware (which should be -1000, if I remember well).

**Comment by Torgan** [comment]
It is indeed :)

**Comment by csarrazi** [comment]
Fixed in #111
