### ISSUE TITLE
Debug middlewares 

### ISSUE THREAD

**Issue by SofHad** [csarrazi/CsaGuzzleBundle#115]
Hi, 
What do you think about adding a ```compilerPass``` to disable the debug middlewares when the profiler is disabled?

**Comment by csarrazi** [comment]
When the profiler is disabled, the debug middleware are actually already disabled.

See https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/DependencyInjection/CsaGuzzleExtension.php#L44

**Comment by SofHad** [comment]
@csarrazi thank you your feedback.
I'm sorry i didn't express myself very clearly, I was talking about the profiler config in ```FrameworkBundle Configuration ```.
http://symfony.com/doc/current/reference/configuration/framework.html#profiler
