### ISSUE TITLE
Modify request?

### ISSUE THREAD

**Issue by peshi** [csarrazi/CsaGuzzleBundle#129]
Some API's use a username / password in the actual query/form_params/json.

From my controller or service I would like to use
```
$client->request('GET', '/', ['json' => ['key' => 'value', 'second_key' => 'second_value']]);
```

But when it is actually sent it should add the username and password key/values.
```
['json' => ['username' => 'john', 'password' => 'doe', 'key' => 'value', 'second_key' => 'second_value']]
```

What would be the best way to do this?

**Comment by csarrazi** [comment]
For this, you should create your own middleware.

To create a middleware, please read the documentation, [here](https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/Resources/doc/middleware.md) and [there](http://guzzle.readthedocs.org/en/latest/handlers-and-middleware.html).

Cheers!

**Comment by peshi** [comment]
@csarrazi Thank you, that worked perfectly!
