### ISSUE TITLE
Bad response when filename is too long with mock record mode

### ISSUE THREAD

**Issue by SiM07** [csarrazi/CsaGuzzleBundle#130]
I have an issue with record mode when the url is very long. I'm on mac and the limit for filename is 255 chars.

The filename is :
$ echo -n "GET____aaa-bbbbbb.search.windows.net_indexes-clips-index-docs-search=--facet-0-=createdAt-interval-day--skip=0--top=3--orderby=createdAt-desc-api-version=2015-02-28--filter=-userId-eq--c65c6f24-33a6-4b3b-b557-aaaaaaaaaaaa--____7e8914e63a4de9a74132056db7b14026.txt" | wc -c
     263

The end of filename is a [md5()](https://github.com/csarrazi/CsaGuzzleBundle/blob/d2dff62f436d14ab0321ef8a558790bd5161be60/src/GuzzleHttp/Cache/MockStorageAdapter.php#L112) I think it's possible to reduce it size to 7 or 8 chars with substr().

**Comment by csarrazi** [comment]
We can do something even better: hash the query params array, or use the same hashing algorithm as the Doctrine cache adapter.

**Comment by csarrazi** [comment]
By the way, feel free to make a pull request! ;)

**Comment by SiM07** [comment]
I develop u develop :)
