### ISSUE TITLE
Adding response times in the collapsed mode

### ISSUE THREAD

**Issue by salahm** [csarrazi/CsaGuzzleBundle#136]
hi :)

It would be great to have response time (right after status code+ reason phrase)  in the collapsed view of the collector. This would be very helpful to have an overview when we're sending few requests from the same page.

**Comment by csarrazi** [comment]
Sure! That's a great idea. This was actually disabled as Guzzle 6.0 didn't provide with a way to detect the request's duration correctly, but that changed with release 6.1.
