### ISSUE TITLE
Allow custom log channel

### ISSUE THREAD

**Issue by markitosgv** [csarrazi/CsaGuzzleBundle#148]
Hi, it would be nice if logger channel can be distinct that "app". To handle logs by channel easier.

**Comment by csarrazi** [comment]
You can actually specify which logger you want to use. This lets you use a logger configured with a specific channel.

**Comment by csarrazi** [comment]
@markitosgv Please check this gist for an example on how to set it up. https://gist.github.com/csarrazi/bb6ac210827973033cbd
