### ISSUE TITLE
"Notice: Undefined index: http_code" when enabling the cache subscriber

### ISSUE THREAD

**Issue by salahm** [csarrazi/CsaGuzzleBundle#15]
Hi,

When enabling the cache subscriber, i'm getting this error on the CsaGuzzleBundle profiler page

![image](https://cloud.githubusercontent.com/assets/1071005/7025273/d9bf79e6-dd42-11e4-9a51-a02d5b76cc33.png)

The `$call['info']` is empty for that case.

**Comment by csarrazi** [comment]
I'll check, but the problem seems to be due to the fact that if you fetch a value from the cache, the curl infos are not available in the array.

**Comment by csarrazi** [comment]
This should be resolved in v1.2.3. Could you check if you still have errors?

**Comment by csarrazi** [comment]
Closing the issue, as we discussed on Slack! :)
