### ISSUE TITLE
Profiler panel is empty

### ISSUE THREAD

**Issue by Tobion** [csarrazi/CsaGuzzleBundle#151]
For me on both Guzzle latest stable as well as dev-master, the Guzzle profiler panel is empty even though there are requests executed (they are logged and in the timeline).

It seems that the `GuzzleCollector::collect` is executed before the history middleware.
So there is no data to collect yet and thus nothing to show.

**Comment by csarrazi** [comment]
This is weird. Do you have some code sample? I can't reproduce the issue locally.

**Comment by Tobion** [comment]
Ah it's probably because the guzzle request is happening in a symfony StreamedResponse. I guess the data collection happens before the response is streamed. Not sure if it has to be like this.

**Comment by csarrazi** [comment]
That's possible. You can also use the `StreamResponse`, provided with the bundle, which actually works with the profiler.

**Comment by csarrazi** [comment]
See https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/HttpFoundation/StreamResponse.php

**Comment by Tobion** [comment]
Thanks for the tip but my case is not about streaming a PSR-7 response. I'm closing this issue as when caused by the StreamedResponse, it's not a bug of your bundle.

**Comment by csarrazi** [comment]
No problem! 🙂
