### ISSUE TITLE
move Tests to tests folder and use composers autoload-dev

### ISSUE THREAD

**Issue by ivoba** [csarrazi/CsaGuzzleBundle#152]
Would you aggree on moving the src/Tests to tests/ and use https://getcomposer.org/doc/04-schema.md#autoload-dev in composer.json.

This would spare some autoload lines.

"Classes needed to run the test suite should not be included in the main autoload rules to avoid polluting the autoloader in production and when other people use your package as a dependency."

**Comment by csarrazi** [comment]
Sure! :)

I just didn't have the time to do it myself. So feel free to make a PR! ;)

**Comment by ivoba** [comment]
Done :)
https://github.com/csarrazi/CsaGuzzleBundle/pull/153
