### ISSUE TITLE
Uncaught ReferenceError: Prism is not defined

### ISSUE THREAD

**Issue by bmancone** [csarrazi/CsaGuzzleBundle#155]
It seems that `guzzle.min.js` in the last stable version was not generated properly : 

```
Uncaught ReferenceError: Prism is not defined
```

Executing `gulp js` fixed the issue.

**Comment by csarrazi** [comment]
Interesting. It's surprising nobody has stumbled upon it before. Will fix during the week. Keep tuned! 😃

**Comment by bmancone** [comment]
Thank you @csarrazi, I'll stay tuned :smiley:

**Comment by csarrazi** [comment]
@bmancone Still having the issue? Could you tell me which exact version you are using? `2.1.x`, or `2.0.x`?

**Comment by bmancone** [comment]
@csarrazi Yes, still having the issue.

Here is my `composer.lock` :

```json
"name": "csa/guzzle-bundle",
"version": "v2.1.0",
"source": {
    "type": "git",
    "url": "https://github.com/csarrazi/CsaGuzzleBundle.git",
    "reference": "ff3da1ed7bf84385d2c6512e0f9777b5e3fbec54"
}
```
