### ISSUE TITLE
[readme] add some screenshot of the profiler panel and more usage example

### ISSUE THREAD

**Issue by allan-simon** [csarrazi/CsaGuzzleBundle#16]
first thanks for the project,  however I think the readme could be made a bit better in order to present fully the capacity of this bundle 

first, while I was trying to decide which guzzle bundle to use (there's quite some),  the guzzle>4 was truly a selling point, but however some others were directly staging and presenting their  symfony2 profiler panel, which I thought at first your project didn't have , stating it clearly with screenshots may help.

also putting a bit more example of usage may also help people (on this regard I found the readme of  https://github.com/LeaseWeb/LswGuzzleBundle quite good), because your readme stop at configurating the service but not on how to use it.

**Comment by csarrazi** [comment]
Indeed, I do agree that it would really help people if there were more screenshots in the README (and more generally speaking, in the rest of the documentation). Features would be also much more obvious.

Thanks for the feedback, @allan-simon! :smile:

**Comment by csarrazi** [comment]
![guzzle-1](https://cloud.githubusercontent.com/assets/465798/7407652/dda8bda4-ef14-11e4-9e9e-1db2fa6a346d.png)
![guzzle-2](https://cloud.githubusercontent.com/assets/465798/7407654/e4432b2c-ef14-11e4-8f84-b11b32dcce86.png)
![guzzle-3](https://cloud.githubusercontent.com/assets/465798/7407656/e7241e14-ef14-11e4-875c-d36ef726679e.png)

**Comment by csarrazi** [comment]
Done! Is that fine for you, @allan-simon? :)

**Comment by allan-simon** [comment]
for the screenshot part yup , it's great ,  for the usage  if you could , replace. 

```
The previous code will create a new service, called csa_guzzle.client.github_api.
```

by a piece of code calling that client, with one line about a guzzle call, so that people can join things in their mind "ok now i got my guzzle stuff i know where to go"

**Comment by csarrazi** [comment]
Done! Anything else?

**Comment by csarrazi** [comment]
Oh, and by the way, I also updated it in the guzzle service description documentation.

**Comment by allan-simon** [comment]
awesome ,  thanks a lot  :+1:
