### ISSUE TITLE
HashNamingStrategy does not work with S3

### ISSUE THREAD

**Issue by cjunge-work** [csarrazi/CsaGuzzleBundle#160]
I'm trying to use the Guzzle client cache middleware with the AWS SDK, and have an issue with the cached response not being used on the next request.

It appears that the ```HashNamingStrategy``` uses all of the headers as part of the value used for the [cache key](https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/Cache/NamingStrategy/HashNamingStrategy.php#L26). The values of the ```aws-sdk-invocation-id```, ```X-Amz-Date``` and ```Authorization``` headers change on each request, and are provided by the SDK.

I can think of two solutions:
* allow white/blacklisting headers to filter out the headers that change;
* allow injecting a custom naming strategy (a service or class).

Would need the cache config entry to be extended to support the additional options.

**Comment by csarrazi** [comment]
Agreed. Do you want to make a PR to support this?

Work could be done to actually merge the cache and mock middleware.

**Comment by cjunge-work** [comment]
I've worked around the issue by extending the DoctrineAdapter class and filtering the request before it's passed to the HashNamingStrategy. I guess that solves the problem!

```
namespace Test;

use Csa\Bundle\GuzzleBundle\GuzzleHttp\Cache\DoctrineAdapter as BaseAdapter;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;

class DoctrineAdapter extends BaseAdapter
{
    /**
     * @inheritdoc
     *
     * @param RequestInterface $request
     *
     * @return \GuzzleHttp\Psr7\Response|null|ResponseInterface
     */
    public function fetch(RequestInterface $request)
    {
        return parent::fetch($this->filterRequest($request));
    }

    /**
     * @inheritdoc
     *
     * @param RequestInterface  $request
     * @param ResponseInterface $response
     */
    public function save(RequestInterface $request, ResponseInterface $response)
    {
        parent::save($this->filterRequest($request), $response);
    }

    /**
     * @param RequestInterface $request
     *
     * @return RequestInterface
     */
    private function filterRequest(RequestInterface $request)
    {
        return $request->withoutHeader('aws-sdk-invocation-id')->withoutHeader('X-Amz-Date')->withoutHeader('Authorization');
    }

}
```

**Comment by csarrazi** [comment]
👍

**Comment by csarrazi** [comment]
👍
