### ISSUE TITLE
History middleware / Guzzle collector and SplObjectStorage 

### ISSUE THREAD

**Issue by Crozin** [csarrazi/CsaGuzzleBundle#161]
History middleware / Guzzle collector uses SplObjectStorage to store information about each request fired by HttpClient. Request objects are immutable (according to PSR7 specification and Guzzle implementation), therefore if any middleware changes a request (e. g. adds a single header) a new request object is created and no information is retreived from SplObjectStorage. This eventually leads to _Notice: Undefined index: response_ in `GuzzleCollector` (https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/DataCollector/GuzzleCollector.php#L68)

**Comment by csarrazi** [comment]
@Crozin This is currently being worked on. See #156

**Comment by Crozin** [comment]
I guess this issue could be closed as duplicate then. I've also tested those changes and everything seems to work just fine. ;-)
