### ISSUE TITLE
Attempted to call an undefined method named "getReasonPhrase"

### ISSUE THREAD

**Issue by ivoba** [csarrazi/CsaGuzzleBundle#164]
Im getting this error after upgrade to 2.1.1:

> UndefinedMethodException in GuzzleCollector.php line 106:
> Attempted to call an undefined method named "getReasonPhrase" of class "GuzzleHttp\Exception\ConnectException".

Im using guzzle 6.2.1.

**Comment by csarrazi** [comment]
I see. It seems that you have a connection exception first, which triggers the error. I'll fix this ASAP

**Comment by ivoba** [comment]
:+1: thanks

**Comment by ivoba** [comment]
i get this again, this time with another exception.

> UndefinedMethodException in GuzzleCollector.php line 105:
> Attempted to call an undefined method named "getReasonPhrase" of class "GuzzleHttp\Exception\RequestException".

**Comment by csarrazi** [comment]
Linked to #181
