### ISSUE TITLE
Extract MockMiddleware

### ISSUE THREAD

**Issue by thewilkybarkid** [csarrazi/CsaGuzzleBundle#169]
I've found `MockMiddleware` really useful when testing applications. I now need its functionality in a non-Symfony project, but requiring this bundle creates a rather large and superfluous dependency tree. Would you be willing to abstract it into a separate library?

**Comment by csarrazi** [comment]
I'm actually considering moving all middleware-related code in a dedicated project. So indeed, it will be done at some point. One thing, though. This won't be until version 3.0 of the bundle.

**Comment by csarrazi** [comment]
Moving the code in another repository will also let some dependencies be suggested instead of required, which should reduce the number of dependencies which need to be installed for third-party projects.

**Comment by thewilkybarkid** [comment]
👍

**Comment by thewilkybarkid** [comment]
For the moment I've included in a few classes in my project with attribution (https://github.com/elifesciences/api-client-php). From my limited understanding of MIT/Apache 2.0 compatibility this is ok, but do let me know if it's not.

**Comment by csarrazi** [comment]
It's fine, no worry!

**Comment by csarrazi** [comment]
Closing as it was implemented in e953bea44 :)
