### ISSUE TITLE
Missing guzzlehttp/log-subscriber in 1.2.4

### ISSUE THREAD

**Issue by wahler** [csarrazi/CsaGuzzleBundle#18]
Hi,

I am having problems with the latest release of the bundle. The error is "Fatal error:  Class 'GuzzleHttp\Subscriber\Log\Formatter' not found in .../src/DependencyInjection/Configuration.php on line 61"

I checked the composer.json of version 1.2.4 and could not find a requirement for `guzzlehttp/log-subscriber` or am I missing something?

**Comment by JordyMoos** [comment]
https://github.com/csarrazi/CsaGuzzleBundle/pull/17

**Comment by csarrazi** [comment]
Do you actually use the `format` key in the logger's configuration? It seems I made a small mistake and accidentally moved some code which should only be in the master branch.

**Comment by csarrazi** [comment]
Can you tell me whether release v1.2.5 fixes the issue?

**Comment by JordyMoos** [comment]
That worked for me
