### ISSUE TITLE
Response Object as Exception

### ISSUE THREAD

**Issue by aliebing** [csarrazi/CsaGuzzleBundle#185]
In case of wrong guzzle call $response object could be exception object from guzzle.
So ReasonPhrase vom $response->getReasonPhrase is not possible to log after request.

**Comment by csarrazi** [comment]
This is already being worked on, and should be fixed by tomorrow. I just need to fix the remaining unit tests.

**Comment by silentgecko** [comment]
We have the same problem here, any update on this task @csarrazi ?

**Comment by jamyouss** [comment]
+1

**Comment by csarrazi** [comment]
Can you check whether PR #186 fixes your issue?

**Comment by csarrazi** [comment]
Ping @aliebing @silentgecko @jamyouss

**Comment by aliebing** [comment]
for me it works now.

**Comment by ivoba** [comment]
Can you make a bug fix release for this, pls.

**Comment by csarrazi** [comment]
No problem. I won't release a full release, but rather a 2.2.0-alpha1 release, during the week. You'll be able to just use the 2.2.0@alpha version in your `composer.json`.

I actually want to finalise support for serialisation before releasing version 2.2.0 :)
