### ISSUE TITLE
Symfony 3.4 / 4.0 compatibility

### ISSUE THREAD

**Issue by skobkin** [csarrazi/CsaGuzzleBundle#211]
When I'm running PHPUnit tests in my CI it fails with current stable `csa/guzzle-bundle 2.2.1` and Symfony 3.4.x-dev (symfony/symfony@e973c247c8) I'm getting an error:

```
PHPUnit 5.7.23 by Sebastian Bergmann and contributors.

......................................                            38 / 38 (100%)

Time: 16.65 seconds, Memory: 40.00MB

OK (38 tests, 86 assertions)

Generating code coverage report in Clover XML format ... done

Remaining deprecation notices (16)

Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since version 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector": 16x
4x in ApplicationAvailabilityFunctionalTest::testPageIsSuccessful from Tests\Skobkin\PointToolsBundle
2x in MainControllerTest::testUserSearch from Tests\Skobkin\PointToolsBundle\Controller
2x in MainControllerTest::testNonExistingUserSearch from Tests\Skobkin\PointToolsBundle\Controller
1x in EventsControllerTest::testHasEvents from Tests\Skobkin\PointToolsBundle\Controller
1x in MainControllerTest::testUserStats from Tests\Skobkin\PointToolsBundle\Controller
1x in MainControllerTest::testAjaxUserAutoComplete from Tests\Skobkin\PointToolsBundle\Controller
1x in MainControllerTest::testAjaxUserAutoCompleteForNonExistingUser from Tests\Skobkin\PointToolsBundle\Controller
1x in PostControllerTest::testNonExistingPostPage from Tests\Skobkin\PointToolsBundle\Controller
1x in PostControllerTest::testShortPostPageIsOk from Tests\Skobkin\PointToolsBundle\Controller
1x in UserControllerTest::testTestuserPageHasHeading from Tests\Skobkin\PointToolsBundle\Controller
1x in UserControllerTest::testTestuserHasSubscribers from Tests\Skobkin\PointToolsBundle\Controller
```

I think this is not a problem of my tests ([`ApplicationAvailabilityFunctionalTest::testPageIsSuccessful`](https://bitbucket.org/skobkin/point-tools/src/527645935f16384c5342f70b13389a45cbef237b/tests/Skobkin/PointToolsBundle/ApplicationAvailabilityFunctionalTest.php?at=master&fileviewer=file-view-default) for example).

Can it be fixed in stable release of this major branch?

**Comment by csarrazi** [comment]
Did you test using `dev-master` or `3.0.0@dev`?

This won't be fixed in branch 2.x. This will only be fixed for version 3.0 of the bundle, which will be released around December.

**Comment by csarrazi** [comment]
FYI, see a874b4a

**Comment by skobkin** [comment]
As I said earlier I was using [`3.4.x-dev`](https://bitbucket.org/skobkin/point-tools/src/527645935f16384c5342f70b13389a45cbef237b/composer.json?at=master&fileviewer=file-view-default#composer.json-16).

> FYI, see a874b4a

Nice! Will it be in the current stable branch of csa/guzzle-bundle (`^2`)?

**Comment by csarrazi** [comment]
Don't worry, you'll be able to use version 3.0 without any major changes. Currently, work is being done to move the middleware out of the bundle, and split them in multiple third-party libraries, in order to facilitate reuse without the bundle.

**Comment by luispabon** [comment]
May I ask how this work is going? We're currently migrating projects to symfony 4 and this is so far the last dependency holding us back.

**Comment by cordoval** [comment]
guyz be patient, it is coming today probably!

**Comment by csarrazi** [comment]
Your wishes have been answered, @luispabon @cordoval @skobkin!

**Comment by cordoval** [comment]
told ya

**Comment by luispabon** [comment]
yay thank you :+1: first proj migrated with zarro boogs
