### ISSUE TITLE
shouldn't we cut a tag already for sf4?

### ISSUE THREAD

**Issue by cordoval** [csarrazi/CsaGuzzleBundle#212]
thanks

**Comment by csarrazi** [comment]
Hi @cordoval. Sorry, but the bundle is currently awaiting some breaking changes, among which separation of the middleware in separate libraries, outside of this bundle.

I won't tag until this is ready, which should be in a few weeks.

Regards,
Charles

**Comment by cordoval** [comment]
few weeks - 6 days now 👍  sf4 is out i can't wait, thanks so much, great bundle!

**Comment by csarrazi** [comment]
@cordoval Could you try whether the current version works for you?

I have pushed the new version, with new dependencies. Support for PHP has been bumped to version 7.1, also.

**Comment by cordoval** [comment]
you mean me to test on dev-master@dev right? because there is no tag yet

**Comment by csarrazi** [comment]
Exactly 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cordoval** [comment]
it works like a charm

**Comment by cordoval** [comment]
related https://github.com/csarrazi/CsaGuzzleBundle/issues/213

**Comment by csarrazi** [comment]
No worry. I was only waiting for confirmation that everything works correctly. I'll tag the libraries at version 1.0.0 in the next hours, followed by the bundle shortly after :)

**Comment by cordoval** [comment]
you got this chief 👍

**Comment by kejwmen** [comment]
thanks! :tada:
