### ISSUE TITLE
forcing the middlewares all

### ISSUE THREAD

**Issue by cordoval** [csarrazi/CsaGuzzleBundle#213]
- Installation request for csa/guzzle-bundle dev-master@dev -> satisfiable by csa/guzzle-bundle[dev-master].

is forcing all middleware packages sad

**Comment by cordoval** [comment]
perhaps middlewares can be moved to suggest?

**Comment by cordoval** [comment]
https://github.com/csarrazi/CsaGuzzleBundle/pull/214

**Comment by csarrazi** [comment]
The separation in multiple packages is only intended for people who are not using the bundle.

The current version of the bundle is plug and play, meaning that all packages should be installed by default. The code of the bundle has not yet been changed yet to check existence or not of the different middleware.

If we move the libraries in suggest, then they won't be automatically installed anymore.

**Comment by cordoval** [comment]
true
