### ISSUE TITLE
Missing declaration for symfony/asset dependency

### ISSUE THREAD

**Issue by ostrolucky** [csarrazi/CsaGuzzleBundle#223]
```
Twig_Error_Syntax:
Did you forget to run "composer require symfony/asset"? Unknown function "asset".

  at vendor/csa/guzzle-bundle/src/Resources/views/Collector/guzzle.html.twig:1
```

**Comment by cordoval** [comment]
no, the asset is not required, you should require it on your own if you are using it

in my project for instance i don't use it

**Comment by ostrolucky** [comment]
Then you also don't use profiler of this bundle? 

Besides, I'm not saying to require symfony/asset. It's fine if you can adjust this bundle to not crash when symfony/asset is missing.

**Comment by cordoval** [comment]
exactly, it is not needed, well it does not crash in my project

**Comment by csarrazi** [comment]
@ostrolucky You just need to set up asset: ~ framework configuration.

Otherwise, you are free to make a PR to remove the need for the asset() helper. Keep in mind that the asset helper is needed as this bundle requires a few JS/CSS dependencies.

**Comment by ostrolucky** [comment]
I use symfony flex. It doesn't install symfony/asset by default and installing it solves this. So it's not a matter of configuration.

I am not going to create PR. I don't even use this bundle. I have installed it just to evaluate it and thought you would like to know problems with it.

**Comment by csarrazi** [comment]
Noted. Thanks for the feedback @ostrolucky!

**Comment by csarrazi** [comment]
As mentioned, the dependency has been added in the suggests section of the composer configuration file. All middleware are optional, as is the profiler. If you do not use the profiler, there is no reason to integrate with the asset helper. Likewise, should you use the web profiler bundle, you only need to add the asset component in require-dev.

**Comment by Tobion** [comment]
Using "suggests" does not help in any way. Noone is actually reading the suggests things and it still fails without manual intervention.
So either make asset a dependency. Or alternatively remove the dependency by inlining assets using twig `include()` instead of `asset()`. This is also done by the webprofiler itself.
