### ISSUE TITLE
Autoconfigure support

### ISSUE THREAD

**Issue by backbone87** [csarrazi/CsaGuzzleBundle#225]
It would be nice if the `ClientInterface` is registered for autoconfiguration (symfony 3.3+)

ref https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L280

**Comment by csarrazi** [comment]
I also agree. That would be a nice addition, after support for auto wiring.

One thing though, I am not sure whether this would not introduce a breaking change, so I would rather present a new config entry (‘csa_guzzle.autoconfigure’), which would be set to false in version 3.1. 

For version 4.0, the value will be switched to ‘true’, or even removed to enable auto config by default.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by backbone87** [comment]
the tag would applied to services with autoconfigure="true". which is a symfony 3.3/3.4+ feature

**Comment by tgalopin** [comment]
I think this can be closed now.
