### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by tristanbes** [csarrazi/CsaGuzzleBundle#230]
Hello,

The last available tag was created **before** this commit 097cf061247164d3728b3caf185685a0b906189d so if you want to use autowiring feature, you must use `-dev` alias.

Can you release a new tag so we can rely on a stable version please ?

**Comment by csarrazi** [comment]
Hi @tristanbes. I will release a new tag once #229 is fixed

**Comment by csarrazi** [comment]
Closing this issue, as version 3.1.0 has just been released.
