### ISSUE TITLE
Reorder middlewares

### ISSUE THREAD

**Issue by coudenysj** [csarrazi/CsaGuzzleBundle#234]
Is there a way to reorder middlewares?

I know you can use the container priority to order custom middlewares, but the default Guzzle middlewares (http_errors, allow_redirects, cookies, prepare_body) are always first, and the CsaGuzzleBundle debug middlewares (stopwatch, history, logger) are always last.

**Comment by coudenysj** [comment]
After digging into the code some more, it is possible to mix the custom middlewares with the  CsaGuzzleBundle debug middlewares.

Since the stopwatch has priority 0:
https://github.com/csarrazi/CsaGuzzleBundle/blob/83b2bc748986c5043fb8ceb62c5ad74f60f8394d/src/Resources/config/middleware.xml#L11

and the history has priority -1000:
https://github.com/csarrazi/CsaGuzzleBundle/blob/83b2bc748986c5043fb8ceb62c5ad74f60f8394d/src/Resources/config/middleware.xml#L16

you can position your custom middlewares.

**Comment by csarrazi** [comment]
Indeed, you can order middleware by changing their priority. If you feel that this is not clear enough, don’t hesitate to add this in the documentation, by the way!

I’m always keen in receiving new PRs :)
