### ISSUE TITLE
Tag a new version for 4.2

### ISSUE THREAD

**Issue by alexdo** [csarrazi/CsaGuzzleBundle#244]
Hi!

Would it be possible to tag a new version that includes the recent Symfony 4.2 deprecation fixes, please? (#240)

We'd love those messages to go away and don't want to rely on -dev aliases :)
Thanks :)

**Comment by csarrazi** [comment]
I will try to create a release some time this week or week-end. If I forget, don't hesitate to ping me again on this thread! :)

**Comment by campings-szanetti** [comment]
Up :)

**Comment by csarrazi** [comment]
Your wish has been granted!
