### ISSUE TITLE
Division by zero warning in profiler for failed requests

### ISSUE THREAD

**Issue by kgilden** [csarrazi/CsaGuzzleBundle#26]
Steps to reproduce:
* Create a request with Guzzle to a host that can't be resolved;
* You should see a `cURL error 6: Couldn't resolve host 'foo'`error;
* Navigate to `_profiler/__token__?panel=guzzle`;

And you're welcomed with

    An exception has been thrown during the rendering of a template ("Warning: Division by zero") in @CsaGuzzle/Calls/call.html.twig at line 26.

This happens because the total request time [here](https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/Resources/views/Calls/macros.html.twig#L74) is zero. Dunno how it should behave though in that case.

**Comment by csarrazi** [comment]
Do you have this on `~1.2.5`?

**Comment by kgilden** [comment]
@csarrazi more or less - this came up when I first tried out #25, which should be based off of master.

**Comment by csarrazi** [comment]
Hum, even with my machine, it takes around 31µs to make a call, with all network interfaces disabled. Regardless, this is an easy fix, I'll release an update for `v1.2.6`.

**Comment by csarrazi** [comment]
Fixed in dee4036

**Comment by csarrazi** [comment]
Tagged in release `v1.2.6`.
