### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by rvanlaak** [csarrazi/CsaGuzzleBundle#260]
Can you tag a new version on the bundle and middleware?

* https://github.com/csarrazi/guzzle-history-middleware/issues/2
* https://github.com/csarrazi/guzzle-cache-middleware/issues/9
* https://github.com/csarrazi/guzzle-stopwatch-middleware/issues/2

**Comment by janvernieuwe** [comment]
+1 I'd like to drop the SF4 deps in my projects.

**Comment by csarrazi** [comment]
Done!
