### ISSUE TITLE
How to upgrade from 2.x to 3.x

### ISSUE THREAD

**Issue by j0k3r** [csarrazi/CsaGuzzleBundle#269]
We are still using the 2.x version and we would like to know how can we upgrade to the 3.x.
The upgrade file doesn't help.

What changed between 2 and 3 version?
Does the upgrade is easy to process?

**Comment by csarrazi** [comment]
Hi @j0k3r . The upgrade procedure is straightforward. The 3.0 version bump was mostly due to the upgraded dependency versions and moving the middleware to separate repositories.

**Comment by j0k3r** [comment]
Such a good news, maybe you should update the upgrade.md with that information avoiding other people to ask it :)

**Comment by csarrazi** [comment]
Definitely!

My only issue is that, I have very little time to contribute to the project anymore as I have many other things to handle these last years.

However, I always take into account pull requests! 😃
