### ISSUE TITLE
Caching middleware & POST parameters

### ISSUE THREAD

**Issue by ProklUng** [csarrazi/CsaGuzzleBundle#276]
Hi! HashNamingStrategy does not take into account $_POST parameters. Solve problem like:

        return md5(serialize([
            'method' => $request->getMethod(),
            'uri' => $request->getUri(),
            'headers' => $request->getHeaders(),
            'post' => (string)$request->getBody(),
        ]));

**Comment by csarrazi** [comment]
Generally speaking, POST requests should not be cached.
