### ISSUE TITLE
Guzzle 404 error

### ISSUE THREAD

**Issue by micayael** [csarrazi/CsaGuzzleBundle#39]
Hi.

In production environment I am configuring monolog to exclude 404 errors but "Csa\Bundle\GuzzleBundle\GuzzleHttp\Subscriber\LoggerSubscriber" logs guzzle 404 errors at onError method, so monolog logs the guzzle and page both 404 errors.

The page is the frontend for some REST services and a 404 error into the service means a 404 error page too.

Is there a way to configure CsaGuzzleBundle to stop logging errors 404? or I should have to override this functionality?

I am using this code into my monolog config

```
excluded_404s:
    - ^/
```

**Comment by csarrazi** [comment]
This should be configured in your logger.

You can use either an activation level, or an activation strategy, if `excluded_404s` does not do the job.
Oh, and FYI, the bundle's log subscriber has been removed in 1.3, as it switched to `guzzlehttp/log-subscriber`. :)

**Comment by micayael** [comment]
@csarrazi you are totally right. I had not seen that update.

I override the Symfony\Bundle\MonologBundle\NotFoundActivationStrategy class with this method and fix the problem.

```php
use GuzzleHttp\Exception\ClientException;
...
public function isHandlerActivated(array $record)
    {
        $isActivated = parent::isHandlerActivated($record);

        if (
            $isActivated
            && $this->request
            && isset($record['context']['exception'])
            && $record['context']['exception'] instanceof HttpException
            && $record['context']['exception']->getStatusCode() == 404
        ) {
            return !preg_match($this->blacklist, $this->request->getPathInfo());
        } elseif (
            $isActivated
            && $this->request
            && isset($record['context']['exception'])
            && $record['context']['exception'] instanceof ClientException
            && $record['context']['exception']->getResponse()->getStatusCode() == 404
        ) {
            return !preg_match($this->blacklist, $this->request->getPathInfo());
        }

        return $isActivated;
    }
 ```
Thanks

**Comment by csarrazi** [comment]
You're welcome! :)
