### ISSUE TITLE
[2.0] Support for Guzzle Services

### ISSUE THREAD

**Issue by csarrazi** [csarrazi/CsaGuzzleBundle#41]
Currently, there is no information about the future of `guzzlehttp/guzzle-services`. For now, support for Guzzle services is not available, and is the only blocking issue until there is further information.

**Comment by ip512** [comment]
:+1:

**Comment by csarrazi** [comment]
Ok. So I decided to drop support for `guzzle/guzzle-services`. We'll re-introduce the library once it is updated for `guzzlehttp/guzzle` `v6.0`.

It's unfortunate, but I don't want to delay this release any longer. This issue will be re-scheduled for another version.
