### ISSUE TITLE
More friendly URLs

### ISSUE THREAD

**Issue by theofidry** [csarrazi/CsaGuzzleBundle#44]
When requesting an URI with query like `GET /api/mandates?filter[order][startAt]=desc`, the effective URL generated for the request is `http://localhost/api/mandates?filter%5Border%5D%5BstartAt%5D=desc`. While it's fine, could it be possible to have the `urldecode()` version displayed in the profiler? The decoded version is... a pain to read.

Using the 1.3 version of the bundle with Guzzle 3.9.

**Comment by csarrazi** [comment]
Sure. This is only an issue with Symfony's escaping, so it should be easy to fix. :)
