### ISSUE TITLE
Error while upgrade from 1.0.3 to dev-master

### ISSUE THREAD

**Issue by iamluc** [csarrazi/CsaGuzzleBundle#5]
It should be written in the doc that the version of guzzle should be choosed in the project, as the bundle is now compatible with Guzzle 4 & 5.

And with guzzle 4, I have this error:

Catchable Fatal Error: Argument 1 passed to Csa\Bundle\GuzzleBundle\GuzzleHttp\Subscriber\StopwatchSubscriber::onFinish() must be an instance of GuzzleHttp\Event\AbstractRetryableEvent, instance of GuzzleHttp\Event\CompleteEvent given, called in /.../vendor/guzzlehttp/guzzle/src/Event/Emitter.php on line 105 and defined

**Comment by csarrazi** [comment]
Fixed in latest commit (8b80728b6f440f0d)
