### ISSUE TITLE
Support Symfony 2.8 / 3.0 profiler

### ISSUE THREAD

**Issue by csarrazi** [csarrazi/CsaGuzzleBundle#57]
Update web debug toolbar and profiler templates to support all versions of Symfony.

* [x] Web debug toolbar
* [x] Profiler panel

**Comment by sroze** [comment]
Looking forward to see this issue closed :+1:

**Comment by csarrazi** [comment]
So do I! ;)

**Comment by csarrazi** [comment]
The pull request is in WIP. Currently, the only missing thing is the backport of the new profiler's tab system, and a few fixes for the accordion.

**Comment by csarrazi** [comment]
Finalised
