### ISSUE TITLE
Upgrade doc

### ISSUE THREAD

**Issue by pierrick-vignand** [csarrazi/CsaGuzzleBundle#6]
Is it possible to have an upgrade documentation from 1.0 to 1.1 ?

Example : https://github.com/symfony/symfony/blob/2.7/UPGRADE-2.6.md

Thanks

**Comment by csarrazi** [comment]
Normally, there should not be any BC change.
Did you run into trouble when installing 1.1?

**Comment by pierrick-vignand** [comment]
Subscribers need a new tag parameter alias

**Comment by csarrazi** [comment]
True! I'll document the changes between the two versions. There are a few other changes, like the removal of the overriden Client class, as well.

**Comment by csarrazi** [comment]
Solved by 7402e1d
