### ISSUE TITLE
[Doc] Improve register bundle example

### ISSUE THREAD

**Issue by JHGitty** [csarrazi/CsaGuzzleBundle#66]
On the current documentation there is this example:
```php
<?php
// in %kernel.root_dir%/AppKernel.php
$bundles[] = new Csa\Bundle\GuzzleBundle\CsaGuzzleBundle();
```

I think we should replace it to this:
```php
$bundles = array(
    // ...
    new Csa\Bundle\GuzzleBundle\CsaGuzzleBundle(),
    // ...
);
```

Reason: I think this bundle is mostly used as normal bundle and not only in dev/test environments.

**Comment by csarrazi** [comment]
Sure! Good feedback!
