### ISSUE TITLE
Server file from remote server

### ISSUE THREAD

**Issue by micayael** [csarrazi/CsaGuzzleBundle#72]
Hi @csarrazi 

I'm using the v1.3.9 of  and I'm trying to get a file from a remote apache server and serve this file to the client like this:

apache -> get request with csaGuzzleBundle -> download to the client

I'm trying to use something like this: https://github.com/csarrazi/CsaGuzzleBundle/blob/1.3/src/Resources/doc/response_streaming.md

```php
$response = $this->getClient()->get('http://drive.google.com/uc?export=view&id=0B2dRtLeD_v77NHpuWk1GdUZoUGs');
return new StreamResponse($response);
```

but I got this error: 

    php.CRITICAL: Fatal Error: Call to a member function seek() on string {"type":1,"file":"/opt/sicp-frontend/vendor/csa/guzzle-bundle/src/HttpFoundation/StreamResponse.php","line":34,"level":-1,"stack":[]} {"token":"562a8421956ea"}

Do you know if this is a bug?

**Comment by csarrazi** [comment]
Hum, which version of Guzzle are you using? If you are using `v4.x`, I suggest you upgrade to guzzle `v5.x` at least, as the `v4.x` branch is no longer maintained by the Guzzle team.

**Comment by csarrazi** [comment]
It seems your bug comes from the fact that your response's body is a string, whereas it should actually be a stream. Do you use any special subscriber?

**Comment by csarrazi** [comment]
@micayael It seems to work perfectly on my side. Could you be a little bit more precise?

**Comment by micayael** [comment]
Hi  @csarrazi.

I have this configuration

```
csa_guzzle:
    profiler: %kernel.debug%
    logger: true
    clients:
        files:
            config:
                base_url: http://drive.google.com
            subscribers:
                debug: true
                stopwatch: true
                logger: true
```

If I try to figure out the content of de body response I get a GuzzleHttp\Stream\Stream instance. 

Looking into my composer.lock I found this version

```
"name": "guzzlehttp/guzzle",
"version": "5.3.0",
"source": {
    "type": "git",
    "url": "https://github.com/guzzle/guzzle.git",
    "reference": "f3c8c22471cb55475105c14769644a49c3262b93"
},
```

**Comment by micayael** [comment]
I think I found something.

I am using a html_compressor fork: https://github.com/micayael/HtmlCompressorBundle

I beleave here is my problem.

**Comment by csarrazi** [comment]
Okay! Keep me posted! :)

**Comment by micayael** [comment]
It works  @csarrazi. My mistake. Thanks

**Comment by csarrazi** [comment]
No problem! :smile:
