### ISSUE TITLE
Update documentation with screenshots of the new profiler panel.

### ISSUE THREAD

**Issue by csarrazi** [csarrazi/CsaGuzzleBundle#83]

**Comment by florianbelhomme** [comment]
OK ?

![guzzle-perf](https://cloud.githubusercontent.com/assets/4208880/12815020/c49fc7ec-cb43-11e5-89c3-93ee82711dc2.jpg)
![guzzle-tab](https://cloud.githubusercontent.com/assets/4208880/12815021/c4a16746-cb43-11e5-9061-f1ea15b04e62.jpg)
![guzzle-toolbar](https://cloud.githubusercontent.com/assets/4208880/12815019/c49faeec-cb43-11e5-9de9-dc3423ea6c35.jpg)

**Comment by csarrazi** [comment]
That's perfect! ;)
