### ISSUE TITLE
Unknown "asset" function in CsaGuzzleBundle:Collector:guzzle.html.twig

### ISSUE THREAD

**Issue by nesl247** [csarrazi/CsaGuzzleBundle#85]
Using Symfony 2.7, I receive `Unknown "asset" function in CsaGuzzleBundle:Collector:guzzle.html.twig at line 54.` on every profiler page.

I tried to find other examples, but I don't see other included profiler pages using `asset()`. Not sure why this doesn't work as I registered this bundle after the twig bundle which has the function.

**Comment by csarrazi** [comment]
Could you show your `framework` configuration key from `config.yml`?

**Comment by csarrazi** [comment]
What happens if you add the following config in `config.yml`?

```yml
framework:
    assets: ~
```

**Comment by csarrazi** [comment]
Ping @nesl247

**Comment by nesl247** [comment]
Sorry, wasn't checking my GH notifications much last night. I tried adding that, and it didn't change anything. I did debug `app/console debug:config framework` without it and the default configuration seems to be there with the empty `packages` array and everything.

**Comment by nesl247** [comment]
Figured out the issue. I was not aware someone else in my dev team decided to use the same service name that was built into symfony for our own assets extension. Now I have some ammunition in which to force them to use namespaces going forward for service names.

**Comment by csarrazi** [comment]
No problem! That must have been a bit tricky to find! ;)

I guess you are not using the `{{ asset() }}` function, right?

**Comment by nesl247** [comment]
Correct, we wrote our own asset functionality. It took way longer than it should have to figure that one out heh.

**Comment by csarrazi** [comment]
There's nothing wrong with overriding the `{{ asset() }}` function. As long as you don't break the contract! ;)

**Comment by nesl247** [comment]
The intention wasn't to override anything. The issue was we were using the same service name.
