### ISSUE TITLE
GuzzleCollector undefined index `response`, and `error`.

### ISSUE THREAD

**Issue by nesl247** [csarrazi/CsaGuzzleBundle#88]
In GuzzleCollector, on line 65 and 66, you are assuming these indexes exist, yet further down, you check if they have any value. If there isn't a response or error, PHP will throw an exception in 7 or a notice in 5. Either way, it's trying to access something that doesn't always exist.

Also, it's generally not a good idea to reuse the same variable name as a method parameter, which you are doing for `$response`.

**Comment by nesl247** [comment]
I'm in Gitter if you wouldn't mind working through debugging all this with me.

**Comment by nesl247** [comment]
And now I feel stupid. It's due to the fact that I was trying to use my own class, which set the curl handler ourselves rather than whatever guzzle uses to select the handler.

**Comment by csarrazi** [comment]
No biggie! And don't worry, there are no stupid questions! :)

**Comment by nesl247** [comment]
Just in case anyone needs to do this in the future, don't just use the guzzle documentation on setting a new handler.

```
$stack = $config['handler'];
$stack->...;
```

**Comment by csarrazi** [comment]
Hum, I could make a few changes so it can work. Can you describe the use case more in detail?

If you wish to use a custom handler, I could make a small development to support defining a handler as a service, or create a handler factory, which could be overriden.

**Comment by nesl247** [comment]
Having handler as an option just like class is would be the best way and would be awesome.

**Comment by csarrazi** [comment]
That could easily be done like this:

```yml
csa_guzzle:
    clients:
        my_client:
            config:
                handler: my.service.id
```

This is not supported currently, but could be, and without too much difficulty.

**Comment by csarrazi** [comment]
One thing, though. We need to make sure that one instance of the service is created each time, when it is injected in the config.

**Comment by csarrazi** [comment]
Actually, it's already the case. However, it is overridden by the compiler pass.

**Comment by csarrazi** [comment]
See https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/DependencyInjection/CompilerPass/MiddlewarePass.php#L106

**Comment by nesl247** [comment]
I knew I had seem it somewhere before.
