### ISSUE TITLE
Question: Does your bundle support $client->postAsync() calls?

### ISSUE THREAD

**Issue by thim81** [csarrazi/CsaGuzzleBundle#93]
I'm looking for Symfony2 bundle that support Async call which is supported by Guzzle.

**Comment by csarrazi** [comment]
Well, the clients created by the bundle are actually Guzzle clients. So if Guzzle supports something, this bundles supports it too.

**Comment by csarrazi** [comment]
FYI, the client class used by the bundle is `GuzzleHttp\Client`, so you should be able to use `sendAsync`, or any `*Asinc` method.

**Comment by thim81** [comment]
It seems something is missing or not working with regards to the Async call.

````
        $client = $this->get('csa_guzzle.client.api_test');
        $promise = $client->postAsync('/api/push/user', ['json' => $msg]);

$promise->then(
                  function (ResponseInterface $res) {
                      var_dump( $res->getStatusCode());
                  },
                  function (RequestException $e) {
                      var_dump($e->getMessage() );
                      var_dump($e->getRequest()->getMethod());
                  }
````

But nothing get printed.

So it seems that the function is called and Guzzle responds but nothing happens.

**Comment by csarrazi** [comment]
You need to unwrap your promise by using the `wait()` method.

`$reponse = $promise->wait();`

If you need to unwrap multiple methods, you can use `GuzzleHttp\Promise\unwrap($promises)`, where `$promises` is an array of promises.

**Comment by csarrazi** [comment]
Keep in mind that PHP is **not** async. Your promise won't be automatically be resolved unless you call the `wait()` method of the promise. And in this case, it will block until the promise is resolved.

**Comment by csarrazi** [comment]
If you need to do **true** async, then you should work with asynchronous workers, or by launching background processes and waiting on them.

Or have logic inside the `then()` method of your promise.

**Comment by csarrazi** [comment]
Please read the Guzzle documentation on this: http://guzzle.readthedocs.org/en/latest/quickstart.html#concurrent-requests

**Comment by thim81** [comment]
I have read the documentation about the async calls and my impression was that you can fire async calls and let php continue without the wait.

Because I want to push data to external API without the current function have to wait for the result, make the whole function slower and I had the impression that this is exactly wait the *Async functions support.
http://docs.guzzlephp.org/en/latest/faq.html#can-guzzle-send-asynchronous-requests

**Comment by thim81** [comment]
To close this issue, your feedback was again helpful.
Adding $promise->wait(); caused the async call to fire properly and the API call was made

```
$client = $this->get('csa_guzzle.client.api_test');
$promise = $client->postAsync('/api/push/user', ['json' => $msg]);
$reponse = $promise->wait();
```
